/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FixturesRouteImport } from './routes/fixtures'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as MainRouteImport } from './routes/main'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as BoysIndexRouteImport } from './routes/boys.index'
import { Route as BoysNbaRouteImport } from './routes/boys.nba'
import { Route as BoysNclRouteImport } from './routes/boys.ncl'
import { Route as GirlsIndexRouteImport } from './routes/girls.index'
import { Route as GirlsNclRouteImport } from './routes/girls.ncl'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesRoute = FixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const BoysIndexRoute = BoysIndexRouteImport.update({
  id: '/boys/',
  path: '/boys/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoysNbaRoute = BoysNbaRouteImport.update({
  id: '/boys/nba',
  path: '/boys/nba',
  getParentRoute: () => rootRouteImport,
} as any)
const BoysNclRoute = BoysNclRouteImport.update({
  id: '/boys/ncl',
  path: '/boys/ncl',
  getParentRoute: () => rootRouteImport,
} as any)
const GirlsIndexRoute = GirlsIndexRouteImport.update({
  id: '/girls/',
  path: '/girls/',
  getParentRoute: () => rootRouteImport,
} as any)
const GirlsNclRoute = GirlsNclRouteImport.update({
  id: '/girls/ncl',
  path: '/girls/ncl',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/fixtures': typeof FixturesRoute
  '/gallery': typeof GalleryRoute
  '/main': typeof MainRoute
  '/results': typeof ResultsRoute
  '/standings': typeof StandingsRoute
  '/boys/nba': typeof BoysNbaRoute
  '/boys/ncl': typeof BoysNclRoute
  '/girls/ncl': typeof GirlsNclRoute
  '/news/$slug': typeof NewsSlugRoute
  '/boys/': typeof BoysIndexRoute
  '/girls/': typeof GirlsIndexRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/fixtures': typeof FixturesRoute
  '/gallery': typeof GalleryRoute
  '/main': typeof MainRoute
  '/results': typeof ResultsRoute
  '/standings': typeof StandingsRoute
  '/boys/nba': typeof BoysNbaRoute
  '/boys/ncl': typeof BoysNclRoute
  '/girls/ncl': typeof GirlsNclRoute
  '/news/$slug': typeof NewsSlugRoute
  '/boys': typeof BoysIndexRoute
  '/girls': typeof GirlsIndexRoute
  '/news': typeof NewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/fixtures': typeof FixturesRoute
  '/gallery': typeof GalleryRoute
  '/main': typeof MainRoute
  '/results': typeof ResultsRoute
  '/standings': typeof StandingsRoute
  '/boys/nba': typeof BoysNbaRoute
  '/boys/ncl': typeof BoysNclRoute
  '/girls/ncl': typeof GirlsNclRoute
  '/news/$slug': typeof NewsSlugRoute
  '/boys/': typeof BoysIndexRoute
  '/girls/': typeof GirlsIndexRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/fixtures'
    | '/gallery'
    | '/main'
    | '/results'
    | '/standings'
    | '/boys/nba'
    | '/boys/ncl'
    | '/girls/ncl'
    | '/news/$slug'
    | '/boys/'
    | '/girls/'
    | '/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/fixtures'
    | '/gallery'
    | '/main'
    | '/results'
    | '/standings'
    | '/boys/nba'
    | '/boys/ncl'
    | '/girls/ncl'
    | '/news/$slug'
    | '/boys'
    | '/girls'
    | '/news'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/fixtures'
    | '/gallery'
    | '/main'
    | '/results'
    | '/standings'
    | '/boys/nba'
    | '/boys/ncl'
    | '/girls/ncl'
    | '/news/$slug'
    | '/boys/'
    | '/girls/'
    | '/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FixturesRoute: typeof FixturesRoute
  GalleryRoute: typeof GalleryRoute
  MainRoute: typeof MainRoute
  ResultsRoute: typeof ResultsRoute
  StandingsRoute: typeof StandingsRoute
  BoysNbaRoute: typeof BoysNbaRoute
  BoysNclRoute: typeof BoysNclRoute
  GirlsNclRoute: typeof GirlsNclRoute
  NewsSlugRoute: typeof NewsSlugRoute
  BoysIndexRoute: typeof BoysIndexRoute
  GirlsIndexRoute: typeof GirlsIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures': {
      id: '/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof FixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boys/': {
      id: '/boys/'
      path: '/boys'
      fullPath: '/boys/'
      preLoaderRoute: typeof BoysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boys/nba': {
      id: '/boys/nba'
      path: '/boys/nba'
      fullPath: '/boys/nba'
      preLoaderRoute: typeof BoysNbaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boys/ncl': {
      id: '/boys/ncl'
      path: '/boys/ncl'
      fullPath: '/boys/ncl'
      preLoaderRoute: typeof BoysNclRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/girls/': {
      id: '/girls/'
      path: '/girls'
      fullPath: '/girls/'
      preLoaderRoute: typeof GirlsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/girls/ncl': {
      id: '/girls/ncl'
      path: '/girls/ncl'
      fullPath: '/girls/ncl'
      preLoaderRoute: typeof GirlsNclRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FixturesRoute: FixturesRoute,
  GalleryRoute: GalleryRoute,
  MainRoute: MainRoute,
  ResultsRoute: ResultsRoute,
  StandingsRoute: StandingsRoute,
  BoysNbaRoute: BoysNbaRoute,
  BoysNclRoute: BoysNclRoute,
  GirlsNclRoute: GirlsNclRoute,
  NewsSlugRoute: NewsSlugRoute,
  BoysIndexRoute: BoysIndexRoute,
  GirlsIndexRoute: GirlsIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
